version: '3.5'
services:
  js:
    build: ./js
    expose:
      - "4001"
      - "4002"
    volumes:
      - js-level-data:/app/db
    external_links:
      - nats
      - mongo

volumes:
  js-level-data:
networks:
  default:
    external:
      name: blue_ocean