package cmc

var stableCons = map[string]bool{
	"USDT" : true,
	"USDC" : true,
	"PAX" : true,
	"BUSD" : true,
	"TUSD" : true,
	"DAI" : true,
	"SAI" : true,
	"XAUT" : true,
	"EURT" : true,
	"QC" : true,
	"EURS" : true,
	"USDK" : true,
	"PAXG" : true,
	"ANCT" : true,
	"XCHF" : true,
	"USDN" : true,
	"GUSD" : true,
	"USDQ" : true,
	"BITCNY" : true,
	"USDX" : true,
	"EOSDT" : true,
	"EBASE" : true,
	"USDS" : true,
	"BITUSD" : true,
	"VNDC" : true,
	"CONST" : true,
	"USNBT" : true,
	"USDH" : true,
	"SDS" : true,
	"BITEUR" : true,
	"NUSD" : true,
	"IDRT" : true,
	"xEUR" : true,
	"BGBP" : true,
	"BRZ" : true,
	"CNYT" : true,
	"CUSD" : true,
	"HKD" : true,
	"HUSD" : true,
	"KRT" : true,
	"UPEUR" : true,
	"UPT" : true,
	"UPUSD" : true,
	"USC" : true,
}
