version: '3.5'

x-common-variables: &env
  CLICKHOUSE: clickhouse
  NATS: nats
  POSTGRES: database:5432

services:
  miner:
    restart: always
    build: radar_miner/.
    environment: *env
  pharos:
    restart: always
    build: pharos/.
    environment: *env
    expose:
      - 8080
      - 8180

networks:
  default:
    external:
      name: blue_ocean